### PR TITLE
Remove conflicting commands 

### PR DESCRIPTION
**Pull request by wrefgtzweve**
These commands already exist and when ran will either not work or run a wrong command.

### CODE REVIEW

**Comment by sarahsturgeon** [comment]
how does this work with https://github.com/CFC-Servers/map_vote/pull/11/files

**Comment by wrefgtzweve** [comment]
Works better but `votemap` would still conflict, i can give fucking with ulx a bit a try

**Comment by sarahsturgeon** [comment]
yeah add that here and i'll close that one

**Review by sarahsturgeon — APPROVED** [review]
Approved pending glualint fix

**Pull request merged**
